-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 11:12:36 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`perfil` ;

CREATE TABLE IF NOT EXISTS `mydb`.`perfil` (
  `id_perfil` INT NOT NULL AUTO_INCREMENT,
  `nivel` VARCHAR(15) NOT NULL,
  `nombres` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `apodo` VARCHAR(50) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(13) NOT NULL,
  `contraseña_encript` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id_perfil`),
  UNIQUE INDEX `apodo_UNIQUE` (`apodo` ASC) VISIBLE,
  UNIQUE INDEX `id_perfil_UNIQUE` (`id_perfil` ASC) VISIBLE,
  UNIQUE INDEX `telefono_UNIQUE` (`telefono` ASC) VISIBLE,
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`peticiones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`peticiones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`peticiones` (
  `id_peticion` INT NOT NULL AUTO_INCREMENT,
  `perfil_id_perfil` INT NOT NULL,
  `mensaje` VARCHAR(256) NOT NULL,
  `archivo` BLOB NULL,
  `fecha` VARCHAR(11) NOT NULL,
  `hora` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id_peticion`),
  UNIQUE INDEX `id_peticion_UNIQUE` (`id_peticion` ASC) VISIBLE,
  INDEX `fk_peticiones_perfil1_idx` (`perfil_id_perfil` ASC) VISIBLE,
  CONSTRAINT `fk_peticiones_perfil1`
    FOREIGN KEY (`perfil_id_perfil`)
    REFERENCES `mydb`.`perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`filtro_archivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`filtro_archivos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`filtro_archivos` (
  `id_filtro` INT NOT NULL AUTO_INCREMENT,
  `id_peticion` INT NOT NULL,
  `id_perfil` INT NOT NULL,
  `fecha` VARCHAR(10) NOT NULL,
  `verificado` TINYINT NULL,
  PRIMARY KEY (`id_filtro`),
  UNIQUE INDEX `id_filtro_UNIQUE` (`id_filtro` ASC) VISIBLE,
  INDEX `fk_filtro_archivos_peticiones1_idx` (`id_peticion` ASC) VISIBLE,
  INDEX `fk_filtro_archivos_perfil1_idx` (`id_perfil` ASC) VISIBLE,
  CONSTRAINT `fk_filtro_archivos_peticiones1`
    FOREIGN KEY (`id_peticion`)
    REFERENCES `mydb`.`peticiones` (`id_peticion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filtro_archivos_perfil1`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `mydb`.`perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`buzon_quejas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`buzon_quejas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`buzon_quejas` (
  `idbuzon_quejas` INT NOT NULL AUTO_INCREMENT,
  `id_perfil` INT NOT NULL,
  `mensaje` VARCHAR(256) NOT NULL,
  `fecha` VARCHAR(11) NOT NULL,
  `hora` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idbuzon_quejas`),
  UNIQUE INDEX `idbuzon_quejas_UNIQUE` (`idbuzon_quejas` ASC) VISIBLE,
  INDEX `fk_buzon_quejas_perfil1_idx` (`id_perfil` ASC) VISIBLE,
  CONSTRAINT `fk_buzon_quejas_perfil1`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `mydb`.`perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categorias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categorias` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `id_categoria_UNIQUE` (`id_categoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subcategorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`subcategorias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`subcategorias` (
  `id_subcategorias` INT NOT NULL AUTO_INCREMENT,
  `subcategoria` VARCHAR(45) NOT NULL,
  `filtro_archivos_id_filtro` INT NOT NULL,
  PRIMARY KEY (`id_subcategorias`),
  UNIQUE INDEX `id_subcategorias_UNIQUE` (`id_subcategorias` ASC) VISIBLE,
  INDEX `fk_subcategorias_filtro_archivos1_idx` (`filtro_archivos_id_filtro` ASC) VISIBLE,
  CONSTRAINT `fk_subcategorias_filtro_archivos1`
    FOREIGN KEY (`filtro_archivos_id_filtro`)
    REFERENCES `mydb`.`filtro_archivos` (`id_filtro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subcategorias-categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`subcategorias-categorias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`subcategorias-categorias` (
  `subcategorias_id_subcategorias` INT NOT NULL,
  `categorias_id_categoria` INT NOT NULL,
  `peticiones_id_peticion` INT NOT NULL,
  PRIMARY KEY (`subcategorias_id_subcategorias`, `categorias_id_categoria`),
  INDEX `fk_subcategorias_has_categorias_categorias1_idx` (`categorias_id_categoria` ASC) VISIBLE,
  INDEX `fk_subcategorias_has_categorias_subcategorias1_idx` (`subcategorias_id_subcategorias` ASC) VISIBLE,
  INDEX `fk_subcategorias-categorias_peticiones1_idx` (`peticiones_id_peticion` ASC) VISIBLE,
  CONSTRAINT `fk_subcategorias_has_categorias_subcategorias1`
    FOREIGN KEY (`subcategorias_id_subcategorias`)
    REFERENCES `mydb`.`subcategorias` (`id_subcategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subcategorias_has_categorias_categorias1`
    FOREIGN KEY (`categorias_id_categoria`)
    REFERENCES `mydb`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subcategorias-categorias_peticiones1`
    FOREIGN KEY (`peticiones_id_peticion`)
    REFERENCES `mydb`.`peticiones` (`id_peticion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mensaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`mensaje` ;

CREATE TABLE IF NOT EXISTS `mydb`.`mensaje` (
  `id_mensaje` INT NOT NULL,
  `id_perfil` INT NOT NULL,
  `mensaje` VARCHAR(256) NOT NULL,
  `fecha` VARCHAR(11) NOT NULL,
  `hora` VARCHAR(12) NOT NULL,
  INDEX `fk_mensaje_perfil1_idx` (`id_perfil` ASC) VISIBLE,
  PRIMARY KEY (`id_mensaje`),
  CONSTRAINT `fk_mensaje_perfil1`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `mydb`.`perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`historial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`historial` ;

CREATE TABLE IF NOT EXISTS `mydb`.`historial` (
  `id_mensaje` INT NOT NULL,
  INDEX `fk_historial_mensaje1_idx` (`id_mensaje` ASC) VISIBLE,
  CONSTRAINT `fk_historial_mensaje1`
    FOREIGN KEY (`id_mensaje`)
    REFERENCES `mydb`.`mensaje` (`id_mensaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
